# Defect Detection

python main.py --gpu 0 --config_name 'attack/generator_defect_classification/exp_noattack/image_defectdetection.yaml'
python main.py --gpu 0 --config_name 'attack/generator_defect_classification/exp_noattack/image_defectdetection_tr_mean.yaml'
python main.py --gpu 0 --config_name 'attack/generator_defect_classification/exp_noattack/image_defectdetection_median.yaml'
python main.py --gpu 0 --config_name 'attack/generator_defect_classification/exp_noattack/image_defectdetection_krum.yaml'
python main.py --gpu 0 --config_name 'attack/generator_defect_classification/exp_noattack/image_defectdetection_bulyan.yaml'
python main.py --gpu 0 --config_name 'attack/generator_defect_classification/exp_noattack/image_defectdetection_flame.yaml'
python main.py --gpu 0 --config_name 'attack/generator_defect_classification/exp_noattack/image_defectdetection_dpfed_NM14.yaml'
python main.py --gpu 0 --config_name 'attack/generator_defect_classification/exp_noattack/image_defectdetection_sparsefed.yaml'

python main.py --gpu 1 --config_name 'attack/generator_defect_classification/exp_nodefend/agrTailoredTrmean_image_defectdetection_attack1.yaml'
python main.py --gpu 1 --config_name 'attack/generator_defect_classification/exp_nodefend/agrTailoredTrmean_image_defectdetection_attack2.yaml'
python main.py --gpu 1 --config_name 'attack/generator_defect_classification/exp_nodefend/agrTailoredTrmean_image_defectdetection_attack3.yaml'
python main.py --gpu 1 --config_name 'attack/generator_defect_classification/exp_nodefend/fang_trmean_median_gray_image_defectdetection_attack1.yaml'
python main.py --gpu 1 --config_name 'attack/generator_defect_classification/exp_nodefend/fang_trmean_median_gray_image_defectdetection_attack2.yaml'
python main.py --gpu 1 --config_name 'attack/generator_defect_classification/exp_nodefend/fang_trmean_median_gray_image_defectdetection_attack3.yaml'

python main.py --gpu 2 --config_name 'attack/generator_defect_classification/exp_attacknum1/agrTailoredKrumBulyan_image_defectdetection_bulyan.yaml'
python main.py --gpu 2 --config_name 'attack/generator_defect_classification/exp_attacknum1/agrTailoredKrumBulyan_image_defectdetection_krum.yaml'
python main.py --gpu 2 --config_name 'attack/generator_defect_classification/exp_attacknum1/agrTailoredMedian_image_defectdetection_median.yaml'
python main.py --gpu 2 --config_name 'attack/generator_defect_classification/exp_attacknum1/agrTailoredTrmean_image_defectdetection_dpfed_NM14.yaml'
python main.py --gpu 2 --config_name 'attack/generator_defect_classification/exp_attacknum1/agrTailoredTrmean_image_defectdetection_flame.yaml'
python main.py --gpu 2 --config_name 'attack/generator_defect_classification/exp_attacknum1/agrTailoredTrmean_image_defectdetection_sparsefed.yaml'
python main.py --gpu 2 --config_name 'attack/generator_defect_classification/exp_attacknum1/agrTailoredTrmean_image_defectdetection_tr_mean.yaml'

python main.py --gpu 3 --config_name 'attack/generator_defect_classification/exp_attacknum1/fang_krum_bulyan_gray_image_defectdetection_bulyan.yaml'
python main.py --gpu 3 --config_name 'attack/generator_defect_classification/exp_attacknum1/fang_krum_bulyan_gray_image_defectdetection_krum.yaml'
python main.py --gpu 3 --config_name 'attack/generator_defect_classification/exp_attacknum1/fang_trmean_median_gray_image_defectdetection_dpfed_NM14.yaml'
python main.py --gpu 3 --config_name 'attack/generator_defect_classification/exp_attacknum1/fang_trmean_median_gray_image_defectdetection_flame.yaml'
python main.py --gpu 3 --config_name 'attack/generator_defect_classification/exp_attacknum1/fang_trmean_median_gray_image_defectdetection_median.yaml'
python main.py --gpu 3 --config_name 'attack/generator_defect_classification/exp_attacknum1/fang_trmean_median_gray_image_defectdetection_sparsefed.yaml'
python main.py --gpu 3 --config_name 'attack/generator_defect_classification/exp_attacknum1/fang_trmean_median_gray_image_defectdetection_tr_mean.yaml'

python main.py --gpu 4 --config_name 'attack/generator_defect_classification/exp_attacknum2/agrTailoredKrumBulyan_image_defectdetection_bulyan.yaml'
python main.py --gpu 4 --config_name 'attack/generator_defect_classification/exp_attacknum2/agrTailoredKrumBulyan_image_defectdetection_krum.yaml'
python main.py --gpu 4 --config_name 'attack/generator_defect_classification/exp_attacknum2/agrTailoredMedian_image_defectdetection_median.yaml'
python main.py --gpu 4 --config_name 'attack/generator_defect_classification/exp_attacknum2/agrTailoredTrmean_image_defectdetection_dpfed_NM14.yaml'
python main.py --gpu 4 --config_name 'attack/generator_defect_classification/exp_attacknum2/agrTailoredTrmean_image_defectdetection_flame.yaml'
python main.py --gpu 4 --config_name 'attack/generator_defect_classification/exp_attacknum2/agrTailoredTrmean_image_defectdetection_sparsefed.yaml'
python main.py --gpu 4 --config_name 'attack/generator_defect_classification/exp_attacknum2/agrTailoredTrmean_image_defectdetection_tr_mean.yaml'

python main.py --gpu 5 --config_name 'attack/generator_defect_classification/exp_attacknum2/fang_krum_bulyan_gray_image_defectdetection_bulyan.yaml'
python main.py --gpu 5 --config_name 'attack/generator_defect_classification/exp_attacknum2/fang_krum_bulyan_gray_image_defectdetection_krum.yaml'
python main.py --gpu 5 --config_name 'attack/generator_defect_classification/exp_attacknum2/fang_trmean_median_gray_image_defectdetection_dpfed_NM14.yaml'
python main.py --gpu 5 --config_name 'attack/generator_defect_classification/exp_attacknum2/fang_trmean_median_gray_image_defectdetection_flame.yaml'
python main.py --gpu 5 --config_name 'attack/generator_defect_classification/exp_attacknum2/fang_trmean_median_gray_image_defectdetection_median.yaml'
python main.py --gpu 5 --config_name 'attack/generator_defect_classification/exp_attacknum2/fang_trmean_median_gray_image_defectdetection_sparsefed.yaml'
python main.py --gpu 5 --config_name 'attack/generator_defect_classification/exp_attacknum2/fang_trmean_median_gray_image_defectdetection_tr_mean.yaml'
