# Ele Theft Detection

python main.py --gpu 0 --config_name 'attack/electricity_theft_detection/exp_noattack/electricity_theft_detection.yaml'
python main.py --gpu 0 --config_name 'attack/electricity_theft_detection/exp_noattack/electricity_theft_detection_tr_mean.yaml'
python main.py --gpu 0 --config_name 'attack/electricity_theft_detection/exp_noattack/electricity_theft_detection_sparsefed.yaml'
python main.py --gpu 0 --config_name 'attack/electricity_theft_detection/exp_noattack/electricity_theft_detection_median.yaml'
python main.py --gpu 0 --config_name 'attack/electricity_theft_detection/exp_noattack/electricity_theft_detection_krum.yaml'
python main.py --gpu 0 --config_name 'attack/electricity_theft_detection/exp_noattack/electricity_theft_detection_flame.yaml'
python main.py --gpu 0 --config_name 'attack/electricity_theft_detection/exp_noattack/electricity_theft_detection_dpfed_NM14.yaml'
python main.py --gpu 0 --config_name 'attack/electricity_theft_detection/exp_noattack/electricity_theft_detection_bulyan.yaml'

python main.py --gpu 1 --config_name 'attack/electricity_theft_detection/exp_nodefend/agrTailoredTrmean_electricity_theft_detection_attack1.yaml'
python main.py --gpu 1 --config_name 'attack/electricity_theft_detection/exp_nodefend/fang_trmean_median_gray__electricity_theft_detection_attack1.yaml'
python main.py --gpu 1 --config_name 'attack/electricity_theft_detection/exp_nodefend/agrTailoredTrmean_electricity_theft_detection_attack2.yaml'
python main.py --gpu 1 --config_name 'attack/electricity_theft_detection/exp_nodefend/fang_trmean_median_gray__electricity_theft_detection_attack2.yaml'

python main.py --gpu 2 --config_name 'attack/electricity_theft_detection/exp_attacknum1/agrTailoredTrmean_electricity_theft_detection_tr_mean.yaml'
python main.py --gpu 2 --config_name 'attack/electricity_theft_detection/exp_attacknum1/agrTailoredTrmean_electricity_theft_detection_sparsefed.yaml'
python main.py --gpu 2 --config_name 'attack/electricity_theft_detection/exp_attacknum1/agrTailoredTrmean_electricity_theft_detection_flame.yaml'
python main.py --gpu 2 --config_name 'attack/electricity_theft_detection/exp_attacknum1/agrTailoredTrmean_electricity_theft_detection_dpfed_NM14.yaml'
python main.py --gpu 2 --config_name 'attack/electricity_theft_detection/exp_attacknum1/agrTailoredMedian_electricity_theft_detection_median.yaml'
python main.py --gpu 2 --config_name 'attack/electricity_theft_detection/exp_attacknum1/agrTailoredKrumBulyan_electricity_theft_detection_krum.yaml'
python main.py --gpu 2 --config_name 'attack/electricity_theft_detection/exp_attacknum1/agrTailoredKrumBulyan_electricity_theft_detection_bulyan.yaml'

python main.py --gpu 3 --config_name 'attack/electricity_theft_detection/exp_attacknum2/agrTailoredTrmean_electricity_theft_detection_tr_mean.yaml'
python main.py --gpu 3 --config_name 'attack/electricity_theft_detection/exp_attacknum2/agrTailoredTrmean_electricity_theft_detection_sparsefed.yaml'
python main.py --gpu 3 --config_name 'attack/electricity_theft_detection/exp_attacknum2/agrTailoredTrmean_electricity_theft_detection_flame.yaml'
python main.py --gpu 3 --config_name 'attack/electricity_theft_detection/exp_attacknum2/agrTailoredTrmean_electricity_theft_detection_dpfed_NM14.yaml'
python main.py --gpu 3 --config_name 'attack/electricity_theft_detection/exp_attacknum2/agrTailoredMedian_electricity_theft_detection_median.yaml'
python main.py --gpu 3 --config_name 'attack/electricity_theft_detection/exp_attacknum2/agrTailoredKrumBulyan_electricity_theft_detection_krum.yaml'
python main.py --gpu 3 --config_name 'attack/electricity_theft_detection/exp_attacknum2/agrTailoredKrumBulyan_electricity_theft_detection_bulyan.yaml'

python main.py --gpu 4 --config_name 'attack/electricity_theft_detection/exp_attacknum1/fang_trmean_median_gray_electricity_theft_detection_tr_mean.yaml'
python main.py --gpu 4 --config_name 'attack/electricity_theft_detection/exp_attacknum1/fang_trmean_median_gray_electricity_theft_detection_sparsefed.yaml'
python main.py --gpu 4 --config_name 'attack/electricity_theft_detection/exp_attacknum1/fang_trmean_median_gray_electricity_theft_detection_median.yaml'
python main.py --gpu 4 --config_name 'attack/electricity_theft_detection/exp_attacknum1/fang_trmean_median_gray_electricity_theft_detection_flame.yaml'
python main.py --gpu 4 --config_name 'attack/electricity_theft_detection/exp_attacknum1/fang_trmean_median_gray_electricity_theft_detection_dpfed_NM14.yaml'
python main.py --gpu 4 --config_name 'attack/electricity_theft_detection/exp_attacknum1/fang_krum_bulyan_gray_electricity_theft_detection_krum.yaml'
python main.py --gpu 4 --config_name 'attack/electricity_theft_detection/exp_attacknum1/fang_krum_bulyan_gray_electricity_theft_detection_bulyan.yaml'

python main.py --gpu 5 --config_name 'attack/electricity_theft_detection/exp_attacknum2/fang_trmean_median_gray_electricity_theft_detection_tr_mean.yaml'
python main.py --gpu 5 --config_name 'attack/electricity_theft_detection/exp_attacknum2/fang_trmean_median_gray_electricity_theft_detection_sparsefed.yaml'
python main.py --gpu 5 --config_name 'attack/electricity_theft_detection/exp_attacknum2/fang_trmean_median_gray_electricity_theft_detection_median.yaml'
python main.py --gpu 5 --config_name 'attack/electricity_theft_detection/exp_attacknum2/fang_trmean_median_gray_electricity_theft_detection_flame.yaml'
python main.py --gpu 5 --config_name 'attack/electricity_theft_detection/exp_attacknum2/fang_trmean_median_gray_electricity_theft_detection_dpfed_NM14.yaml'
python main.py --gpu 5 --config_name 'attack/electricity_theft_detection/exp_attacknum2/fang_krum_bulyan_gray_electricity_theft_detection_krum.yaml'
python main.py --gpu 5 --config_name 'attack/electricity_theft_detection/exp_attacknum2/fang_krum_bulyan_gray_electricity_theft_detection_bulyan.yaml'
