_base_ : ['../../../defense/flame.yaml']

############## base differential #############
num_users: 20 # number of users: K
num_selected_users: 5 # number of selected users: 100, for shakespeare, it is 10
round: 180 # rounds of training
tau: 1
batch_size: 64 # local batch size
local_lr: 0.01 # local learning rate
local_momentum: 0.5 # SGD Momentum default 0.5
decay_weight: 0.99 # learning rate decay weight default 0.5
global_momentum: 0.9 # global momentum
clip: 1 # clipping threshold
########### base differential ends ###########

method: attack_defense_fedavg
attack: agrTailoredTrmean
defend: flame
# Model
model: cnn_defectclassification

# Dataset configure
data_type: image
dataset: generator_defect_classification
iid: 1 # whether i.i.d or not

# Attack method
num_attackers: 1 # number of attackers